#!/usr/bin/env python3

class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


import os
import time
from glob import glob
import sys
from types import SimpleNamespace as SN

def gtimes(filename):
	mod_time = os.path.getmtime(filename)
	mod_time_str = time.strftime("%Y-%m-%d", time.localtime(mod_time))
	return (mod_time_str, filename)

res = [gtimes(filename) for filename in glob(sys.argv[1] + "/*")]
res = sorted(res,key=lambda x: x[0])
for r in res: print(f"{bcolors.OKCYAN}{r[0]:14s}{bcolors.ENDC} {r[1]}")

